"""empty message

Revision ID: 213e36a0b113
Revises: 74d0a5f33cef
Create Date: 2022-06-26 17:48:14.757812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '213e36a0b113'
down_revision = '74d0a5f33cef'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
