"""empty message

Revision ID: 5f38bfe6e4a6
Revises: 213e36a0b113
Create Date: 2022-06-26 18:24:26.326046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f38bfe6e4a6'
down_revision = '213e36a0b113'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
