"""empty message

Revision ID: 74d0a5f33cef
Revises: aa9424c781da
Create Date: 2022-06-26 16:56:50.434594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74d0a5f33cef'
down_revision = 'aa9424c781da'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
