"""empty message

Revision ID: d1e8e8e64e67
Revises: 5f38bfe6e4a6
Create Date: 2022-06-26 18:32:34.883223

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1e8e8e64e67'
down_revision = '5f38bfe6e4a6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
