"""First migration

Revision ID: e05861283c0c
Revises: d1e8e8e64e67
Create Date: 2022-06-26 18:33:49.239658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e05861283c0c'
down_revision = 'd1e8e8e64e67'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
